[tool.tartufo]
repo-path = '.'
regex = true
entropy = true

exclude-path-patterns = [
    {path-pattern = 'uv\.lock$', reason = 'uv lock file'},
    {path-pattern = '.*package-lock\.json$', reason = 'npm lock file'},
    {path-pattern = 'tartufo\.toml$', reason = 'Tartufo config file'},
]

exclude-entropy-patterns = [
    # {path-pattern = '', pattern = '', reason = ''},
]

exclude-signatures = [
    {signature = '133f866ac4d1c086e5efc4f059cae9f2ad928462f1364c083a38b6a27ea5fb6a', reason = 'example server ID is not credential'},
    {signature = '48262775df5e0ffc9e0050332701dfaf7d7637f248314030dadb86af47177272', reason = 'OpenAI model name is not credential'},
    {signature = 'f21bc298b18aa023df145ffa17620b99de81d12f2d2de22d39792eba522bc2ce', reason = 'OpenAI model name is not credential'},
    {signature = 'beadb94550926b86a537f2aca22e84164e8ac0ab9762fa369026476d305bde35', reason = 'OpenAI model name is not credential'},
    {signature = 'cabf363f5c4b5dcbd4c84ca305c200eb1de8cb97222e16606d7f2d83c7f90fd5', reason = 'example user ID is not credential'},
    {signature = 'f0bf889fbb263b82e226ba1fec8e33514cb435244fd8a271ade0899160199dd3', reason = 'MongoDB URI template is not credential'},
    {signature = '401b06103097ffe15734419a65da63877defd9b4bbf9fb961e0625111cdb6812', reason = 'public URL is not credential'},
    {signature = '7e1c4628cc213c5896e08f35c7b5837c00577bf22c0dda0a52169662d5659471', reason = 'public URL is not credential'},
    {signature = '8c376644d74fa3d82a64e5bbf7290a0af7b37f88986db19ffdae8aba3173d6fb', reason = 'public URL is not credential'},
]
